default: &default
  adapter: mysql2
  pool: 5
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4

ci: &ci
  host: 127.0.0.1
  username: root

development:
  <<: *default
  database: djjson_development

test:
  <<: *default
  <% if ENV['CI'] %>
  <<: *ci
  <% end %>
  database: djjson_test

production:
  <<: *default
  database: djjson_production
